### ISSUE TITLE
Mouse interactions do not appear to be working properly

### ISSUE THREAD

**Issue by dparnell** [zacps/alacritty#19]
Which operating system does the issue occur on?

Windows 10 client connecting to a Linux 16.04 machine via ssh

Steps to reproduce:

1. Make sure that `dialog` is installed
2. Execute `dialog --yesno Testing 10 30`
3. Attempt to use the mouse to click on either the Yes or No button. Nothing happens

Expected bahavior:

Clicking on either of the buttons should cause the `dialog` process to exit

**Comment by zacps** [comment]
Does this work in native cmd?
Does it work with native windows programs that interact with the mouse? (Not over SSH)

**Comment by dparnell** [comment]
I just tried it using a ssh connection from a Poweshell window and it does not work there either.
I'll have to see if I can find a windows command line app that does mouse interaction.

**Comment by parthsdoshi** [comment]
Here's a test case that works using cmd.exe but not with alacritty.exe:

1. Run `bash`
2. Run `tmux`
3. Make sure tmux mouse mode is on: `<Leader> :set -g mouse on`
4. Run `dialog --yesno Testing 10 30`
5. Verify clicking works using cmd.exe
6. Detach tmux: `<Leader> d`
7. open alacritty.exe
8. Run `bash`
9. Run `tmux a`
10. Run `dialog --yesno Testing 10 30`
11. Verify the same does not work in alacritty.

There's a few simpler test cases too.
Open bash through cmd.exe and test vim scrolling. Do the same in alacritty.exe and see that vim won't receive any mouse input.

**Comment by dparnell** [comment]
The mouse works as expected on other platforms (Linux and MacOS) so this is a Windows issue

**Comment by zacps** [comment]
Migrated to https://github.com/jwilm/alacritty/issues/1663
