### ISSUE TITLE
Any kind of vague list regarding what still needs to be fixed?

### ISSUE THREAD

**Issue by Vatyx** [zacps/alacritty#2]
In your comment linking this repo you mention there's a lot of work that still needs to be done. Do you have a vague list of what things still need to be changed?

Also it seems that your fork still fails for me on building servo-fontconfig. Did you switch to a different create locally or are using something different for rendering?

**Comment by zacps** [comment]
The servo-fontconfig issue is a missing library iirc. There's documentation for what's needed on that project's page.

Because I only know something is wrong if it fails I can't produce a list of things still to do.
Any out standing issues that I can move past without resolving will be listed here. At the moment I'm working on the font system.

**Comment by zacps** [comment]
The other thing is to refractor the interface between tty.rs and event_loop.rs to make it as easy as possible to add more sources (In preparation for the powershell changes).

The final two things are to make sure it works on Linux (I probably clobbered some stuff) and to make sure the appveyor build works.

**Comment by Vatyx** [comment]
Are you switching the system over to ClearType?

The documentation mostly deals with installing FreeType or fontconfig from package managers. What did you do to get to to compile initially?

**Comment by zacps** [comment]
Nope, if someone wants to implement that it's fine with me but the initial implementation is rusttype.
The build will fail on [servo-fontconfig-sys](https://github.com/servo/libfontconfig/) and that's where you need to read the install instructions.

**Comment by zacps** [comment]
There's now a larger list of issues that you could help with, check out the [help-wanted label](https://github.com/zacps/alacritty/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).
