### ISSUE TITLE
256 colours are not supported in bash on windows

### ISSUE THREAD

**Issue by BartXZX** [zacps/alacritty#24]
Which operating system does the issue occur on?
Windows 10 - WSL

I tried the last compiled build from AppVeyor, but the colors don't seem to be displayed correctly. This is what it looks like:
![image](https://user-images.githubusercontent.com/5583518/43946261-075bbab8-9c85-11e8-93f8-f5f5bffbd19d.png)

This is what it looks like on [wsltty](https://github.com/mintty/wsltty):
![image](https://user-images.githubusercontent.com/5583518/43946338-4cff2fdc-9c85-11e8-9991-8d59bc555f6e.png)

As a side question. I am starting bash by simply typing 'bash' in de cmd prompt that starts. Would this be the proper way?

**Comment by zacps** [comment]
Thanks for the report!

If you always want to start bash you can use the `shell.program` config key to start it all of the time.

Downstream issue: https://github.com/rprichard/winpty/issues/108

**Comment by BartXZX** [comment]
I [see](https://github.com/Microsoft/console/issues/57#issuecomment-373530472) that you've been looking into this as well. Thanks for the response!

**Comment by zacps** [comment]
Migrated to https://github.com/jwilm/alacritty/issues/1662
