### ISSUE TITLE
Buffer is Stretched With Intel HD Graphics

### ISSUE THREAD

**Issue by jcdickinson** [zacps/alacritty#26]
## System

Windows 10 with Intel HD Graphics P630

## Description

The buffer seems stretched when using Intel HD Graphics. The origin for this stretch seems to be centered around 0.5, 0.5 - leading characters to fall outside the terminal window and the text to be blurry:

![Stretched Buffer](https://user-images.githubusercontent.com/522465/45838229-1401aa00-bcc6-11e8-8020-340d2ec2902c.png)

I've messed about with DPI settings and that seems to have _no_ effect (my DPI is 100% in any case).

## Workaround

The issue disappears if I allocate my NVIDIA (presumably AMD would work too) chip to Alacritty:

![Rendered with real GPU](https://user-images.githubusercontent.com/522465/45838608-fda81e00-bcc6-11e8-8833-8d2fa1fe99ae.png)

**Comment by zacps** [comment]
Wow nice catch! I have absolutely no idea what could be causing this but I'll see if I can reproduce it.

**Comment by jcdickinson** [comment]
I might be able to help investigate this further, if you could let me know how you're debugging or tracing; I'm a completely green Rust developer.

Edit: after a little more investigation the texture seems to be aligned with the full window (i.e. including the chrome). Could be a glutin issue.

Edit: yep, removing the chrome resolves the issue. I'm having a look at updating glutin to 0.18 on the off-chance that this has been resolved.

Edit: *[my awfully hacked together]* glutin update to 0.18 makes no difference.

**Comment by zacps** [comment]
First could you try running the [rusttype](https://github.com/redox-os/rusttype) examples and see if they produce something similar on your integrated GPU?.

If those work fine it's probably an issue in the renderer (`src/render/mod.rs`) rather than rusttype's rasterizing, but it could also be a slip-up I made in `font/src/rusttype/mod.rs`.

**Comment by jcdickinson** [comment]
Thanks, that's useful.

The rusttype GPU cache does the same thing. I followed the rabbit hole all the way down to glutin, I'll log a bug over there - but the glutin cargo will likely need to be updated here once they resolve the issue.

**Comment by jcdickinson** [comment]
It's an Intel issue - Intel HD is the *worst.* The [24.20.100.6286 drivers](https://downloadcenter.intel.com/download/27988/Intel-Graphics-Driver-for-Windows-10?product=98913) (latest) fix the problem.
