### ISSUE TITLE
Document process for setting up all dev dependencies

### ISSUE THREAD

**Issue by zacps** [zacps/alacritty#4]
Unfortunately `cargo build` is not quite enough to setup all dependencies.
Winpty requires msbuild and fontconfig-sys requires a library from *somewhere* (See servo-fontconfig-sys repo).
Bindgen also relies on llvm being installed.

**Comment by Kethku** [comment]
just running cargo from your cloned repo also seems to complain about cmake missing to compile expat-sys. Dunno what thats about but probably something more needs set up.

**Comment by zacps** [comment]
Then install cmake and document the process for it.
Almost all dependencies are compile-time rather than run-time.

**Comment by Kethku** [comment]
My apologies. In rereading my comment, I come across as super entitled. I will do this

**Comment by zacps** [comment]
Don't worry about it :)
All help is appreciated.

**Comment by zacps** [comment]
The current readme in the windows-linux branch should have all required setup information.
